import os
import cv2
import mediapipe as mp
import numpy as np
import urllib.request
from typing import Dict, Any, List

class PoseEstimator:
    def __init__(self, static_image_mode=False, min_detection_confidence=0.5, min_tracking_confidence=0.5):
        # We need the model task file for MediaPipe Tasks API.
        self.model_path = os.path.join(os.path.dirname(__file__), "pose_landmarker_heavy.task")
        if not os.path.exists(self.model_path):
            print("Downloading pose_landmarker_heavy.task...")
            urllib.request.urlretrieve(
                "https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_heavy/float16/1/pose_landmarker_heavy.task",
                self.model_path
            )

        BaseOptions = mp.tasks.BaseOptions
        PoseLandmarker = mp.tasks.vision.PoseLandmarker
        PoseLandmarkerOptions = mp.tasks.vision.PoseLandmarkerOptions
        VisionRunningMode = mp.tasks.vision.RunningMode

        options = PoseLandmarkerOptions(
            base_options=BaseOptions(model_asset_path=self.model_path),
            running_mode=VisionRunningMode.IMAGE,
            min_pose_detection_confidence=min_detection_confidence,
            min_pose_presence_confidence=min_tracking_confidence,
            min_tracking_confidence=min_tracking_confidence
        )
        self.landmarker = PoseLandmarker.create_from_options(options)

        # Landmarks to extract based on requirements (MediaPipe Pose has 33 landmarks)
        self.key_landmarks = {
            "nose": 0,
            "left_shoulder": 11,
            "right_shoulder": 12,
            "left_elbow": 13,
            "right_elbow": 14,
            "left_wrist": 15,
            "right_wrist": 16,
            "left_hip": 23,
            "right_hip": 24,
            "left_knee": 25,
            "right_knee": 26,
            "left_ankle": 27,
            "right_ankle": 28,
            "left_foot_index": 31,
            "right_foot_index": 32
        }

    def process_frame(self, frame: np.ndarray) -> Dict[str, Any]:
        """
        Process a single frame to extract pose landmarks.
        """
        image_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=image_rgb)
        
        results = self.landmarker.detect(mp_image)
        
        extracted_landmarks = {}
        detected = False
        
        if results.pose_landmarks and len(results.pose_landmarks) > 0:
            landmarks = results.pose_landmarks[0]
            # Key running landmarks: shoulders (11,12), hips (23,24), knees (25,26), ankles (27,28)
            key_ids = [11, 12, 23, 24, 25, 26, 27, 28]
            visibilities = [landmarks[idx].visibility for idx in key_ids if hasattr(landmarks[idx], 'visibility')]
            avg_vis = sum(visibilities) / len(visibilities) if visibilities else 1.0

            if avg_vis >= 0.5:
                detected = True
                for name, lm_id in self.key_landmarks.items():
                    lm = landmarks[lm_id]
                    extracted_landmarks[name] = {
                        "x": lm.x,
                        "y": lm.y,
                        "z": lm.z,
                        "visibility": getattr(lm, 'visibility', 1.0)
                    }
                
        return {
            "detected": detected,
            "landmarks": extracted_landmarks,
            "raw_results": results # In case we need to draw it later
        }

    def draw_landmarks(self, frame: np.ndarray, results) -> np.ndarray:
        """
        Draw landmarks on the frame for visualization using OpenCV dots.
        """
        annotated_frame = frame.copy()
        h, w, _ = annotated_frame.shape
        
        if results.pose_landmarks and len(results.pose_landmarks) > 0:
            landmarks = results.pose_landmarks[0]
            for lm in landmarks:
                x = int(lm.x * w)
                y = int(lm.y * h)
                if 0 <= x < w and 0 <= y < h:
                    cv2.circle(annotated_frame, (x, y), 3, (0, 255, 0), -1)
                    
        return annotated_frame

    def extract_video_poses(self, frame_generator, total_frames: int = 0) -> Dict[str, Any]:
        """
        Extract poses from all frames generated by a frame generator.
        """
        frame_poses = []
        detection_count = 0
        total_processed = 0
        
        for frame_idx, frame in frame_generator:
            total_processed += 1
            pose_data = self.process_frame(frame)
            
            if pose_data["detected"]:
                detection_count += 1
                
            frame_poses.append({
                "frame_idx": frame_idx,
                "detected": pose_data["detected"],
                "landmarks": pose_data["landmarks"]
            })
            
        detection_rate = (detection_count / total_processed * 100) if total_processed > 0 else 0
        
        return {
            "detection_rate": detection_rate,
            "total_processed_frames": total_processed,
            "frames": frame_poses
        }
